### ISSUE TITLE
Not getting the correct hex value

### ISSUE THREAD

**Issue by ghost** [TimPietrusky/randomstringtocsscolor#1]
If I input "boo", I get the incorrect hex value - `#b00000`.

Input: "boo". Change each non-hex character to a 0.
Get "b00". Add 0's to the string until its length is a multiple of 3. Already is. Divide string into 3 equal parts. Length of each substring is 1. So the hex is `#b00` which is equivalent to `#bb0000`, not to `#b00000`.

And it's obviously not getting the right `rgb` value either, since `b0` is `176` and `bb` is `187`.

**Comment by TimPietrusky** [comment]
Yes. You are right. :D

**Comment by TimPietrusky** [comment]
@thebabydino can you please verify this?

**Comment by ghost** [comment]
Seems fine to me now.
